In [4]:
import numpy as np


In [18]:
def potential_method_phase_1(a, b):
    m = len(a)
    n = len(b)
    
    i = 0
    j = 0
    
    x = np.zeros((m, n))
    base = []
    
    while i < m and j < n:
        mn = min((a[i], b[j]))
        a[i] -= mn
        b[j] -= mn
        x[i, j] = mn
        base.append((i, j))
        if a[i] == 0:
            i += 1
        else:
            j += 1
        
    return x, base

In [61]:
def find_angle_nodes(b):
    base = b.copy()
    while True:
        deleted = False
        
        num_in_row = {}
        for i, j in base:
            if i in num_in_row:
                num_in_row[i] += 1
            else:
                num_in_row[i] = 1
                
        for row, num in num_in_row.items():
            if num <= 1:
                base = list(filter(lambda t: t[0] != row, base))
                deleted = True
                
        num_in_col = {}
        for i, j in base:
            if j in num_in_col:
                num_in_row[j] += 1
            else:
                num_in_row[j] = 1
        
        for col, num in num_in_col.items():
            if num <= 1:
                base = list(filter(lambda t: t[1] != col, base))
                deleted = True
                
        if not deleted:
            break
    
    return base


In [68]:
def potential_method_phase_2(a, b, c):
    m = len(a)
    n = len(b)
    
    u = np.zeros(m)
    v = np.zeros(n)
    
    x, base = potential_method_phase_1(a, b)
    
    while True:
        base = sorted(base)
        
        found_u = [False for i in range(m)]
        found_v = [False for i in range(n)]

        found_u[0] = True
        u[0] = 0
        
        while not all(found_u) or not all(found_v):
            for i, j in base:
                if found_u[i]:
                    v[j] = c[i, j] - u[i]
                    found_v[j] = True
                else if found_v[j]:
                    u[i] = c[i, j] - v[j]
                    found_u[i] = True
        
        optimal = True
        new_base = None
        for i in range(m):
            for j in range(n):
                if (i, j) not in base and u[i] + v[j] > c[i, j]:
                    optimal = False
                    new_base = (i, j)
                    break
            if not optimal:
                break
                
        print(found_u)
        print(found_v)

        if optimal:
            return x
        else:
            print(f"new: {new_base}")
        
        k = np.zeros((m, n))
        
        base.append(new_base)
        
        l = {}
        r = {}
        u = {}
        d = {}
        for i in range(m):
            left = None
            for j in range(n):
                if (i, j) in base:
                    if left:
                        r[left] = (i, j)
                        l[(i, j)] = left
                    left = (i, j)
                    
        for j in range(n):
            up = None
            for i in range(m):
                if (i, j) in base:
                    if up:
                        d[up] = (i, j)
                        u[(i, j)] = up
                    up = (i, j)
            
        cx, cy = new_base
        ck = 1
        while True:
            k[cx, cy] = ck
            ck *= -1
            found = False
            for side in [l, r, u, d]:
                if (cx, cy) in side and k[side[(cx, cy)]] == 0:
                    found = True
                    cx, cy = side[(cx, cy)]
                    break

            if not found:
                break
        
        omega = np.inf
        for i in range(m):
            for j in range(n):
                if k[i, j] == -1:
                    omega = min((omega, x[i, j]))
                    
        print(f"Omega is: {omega}")
        
        for i in range(m):
            for j in range(n):
                x[i, j] += k[i, j] * omega
        
        angle_nodes = find_angle_nodes(base)
        for i, j in angle_nodes:
            if x[i, j] == 0:
                base.remove((i, j))
                break
        
        print(f"Base is: {base}")
        print(f"X is: {x}")
        

SyntaxError: expected ':' (2503322810.py, line 24)

In [69]:
a = np.array([100, 300, 300])
b = np.array([300, 200, 200])
c = np.array(
    [
        [8, 4, 1],
        [8, 4, 3],
        [9, 7, 5]
    ]
)
print(potential_method_phase_2(a, b, c))

[True, True, True]
[True, True, True]
new: (0, 2)
Omega is: 100.0
Base is: [(1, 0), (1, 1), (2, 1), (2, 2), (0, 2)]
X is: [[  0.   0. 100.]
 [300.   0.   0.]
 [  0. 200. 100.]]
[True, True, True]
[False, True, True]
new: (2, 0)
Omega is: 100.0
Base is: [(0, 2), (1, 0), (2, 1), (2, 2), (2, 0)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 1)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 1)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 2)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 2)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 1)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 1)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 2)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 2)]
X 

X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 2)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 2)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 1)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 1)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 2)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 2)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 1)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 1)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 2)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 2)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 1)
Omega is

Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 1)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 2)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 2)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 1)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 1)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 2)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 2)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 1)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 1)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 2)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 2)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 20

[True, True, True]
[False, True, True]
new: (0, 1)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 1)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 2)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 2)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 1)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 1)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 2)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 2)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 1)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 1)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 2)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 2)]
X is:

X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 2)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 2)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 1)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 1)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 2)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 2)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 1)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 1)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 2)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 2)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 1)
Omega is

Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 1)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 2)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 2)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 1)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 1)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 2)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 2)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 1)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 1)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 2)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 2)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 20

X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 2)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 2)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 1)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 1)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 2)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 2)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 1)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 1)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 2)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 2)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 1)
Omega is

X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 1)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 1)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 2)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 2)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 1)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 1)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 2)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 2)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 1)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 1)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 2)
Omega is

Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 1)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 2)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 2)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 1)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 1)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 2)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 2)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 1)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 1)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 2)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 2)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 20

X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 1)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 1)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 2)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 2)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 1)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 1)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 2)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 2)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 1)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 1)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 2)
Omega is

X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 1)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 1)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 2)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 2)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 1)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 1)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 2)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 2)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 1)
Omega is: 0.0
Base is: [(1, 0), (2, 0), (2, 1), (2, 2), (0, 1)]
X is: [[  0.   0.   0.]
 [300.   0.   0.]
 [100. 100. 200.]]
[True, True, True]
[False, True, True]
new: (0, 2)
Omega is

KeyboardInterrupt: 